[package]
name = "mandelbrot-cpu"
version.workspace = true
edition.workspace = true

[dependencies]
mandelbrot-core = { path = "../core" }
num-complex = "0.4"
rayon = "1.10.0"
tokio = { version = "1", features = ["macros", "rt"] }
wide = "1.7.0"

[[bin]]
name = "mandelbrot-cpu-parallel"
path = "src/bin/parallel.rs"

[[bin]]
name = "mandelbrot-cpu-sequential"
path = "src/bin/sequential.rs"

[[bin]]
name = "mandelbrot-cpu-simd"
path = "src/bin/simd.rs"